name: Test Secrets

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exist
        run: |
          if [ -n "${{ secrets.AMO_JWT_ISSUER }}" ] && [ -n "${{ secrets.AMO_JWT_SECRET }}" ]; then
            echo "✅ Both AMO_JWT_ISSUER and AMO_JWT_SECRET secrets are available!"
          else
            echo "❌ One or both secrets are missing!"
            if [ -z "${{ secrets.AMO_JWT_ISSUER }}" ]; then
              echo "AMO_JWT_ISSUER is missing"
            fi
            if [ -z "${{ secrets.AMO_JWT_SECRET }}" ]; then
              echo "AMO_JWT_SECRET is missing"
            fi
            exit 1
          fi